### ISSUE TITLE
Statistic page needs Overhaul

### ISSUE THREAD

**Issue by lukasmartinelli** [studentenportal/web#143]
Created from remark in #139

Add some spacing and simply make it a bit more beautiful.

**Comment by dbrgn** [comment]
Please reactivate the statistics page :)

**Comment by dbrgn** [comment]
It's still here, just not linked: https://studentenportal.ch/statistiken/

**Comment by lukasmartinelli** [comment]
Wir können es im Footer verlinken.

Aus der Hauptnavigation war es weg weil nur eine Person in mehreren Monaten
die Statistik angeschaut hat.

**Comment by dbrgn** [comment]
> Aus der Hauptnavigation war es weg weil nur eine Person in mehreren Monaten

Echt? Ich habe ja nur die Statistiken bis im August 2014, aber im letzten Jahr gab es darauf 789 page hits.

Footer finde ich aber gut. Einfach darauf achten dass es nur für eingeloggte Personen angezeigt wird.
