### ISSUE TITLE
Switch to Semantic Versioning

### ISSUE THREAD

**Issue by lukasmartinelli** [studentenportal/web#161]
At the moment our `setup.py` uses the git revision number as version.
```python
VERSION = subprocess.check_output(['git', 'rev-list', 'HEAD', '--count']).strip()
```
This definitly works but I propose to switch to [semantic versioning](http://semver.org/), so we can create github releases and tags accordingly (helps to know which bugs have been fixed and deployed).

I think the current version would be something like `v2.1.0`

**Comment by saspeed** [comment]
I can't see a reason for as long as we don't provide a package for external usage. Therefore I close this issue to reopen it only in the event of a major strategy change.
