### ISSUE TITLE
TLS Zertifikat im Jahr 2015 updaten

### ISSUE THREAD

**Issue by dbrgn** [studentenportal/web#170]
https://www.ssllabs.com/ssltest/analyze.html?d=studentenportal.ch&hideResults=on

![img](http://tmp.dbrgn.ch/screenshots/20141209_131708.png)

Das letzte Cert wurde vom VSHSR gesponsert. Könnte er ev wieder tun.

**Comment by lukasmartinelli** [comment]
Ja jetzt motzt Chrome. Werde mich darum kümmern.

**Comment by dbrgn** [comment]
Any updates? :)

**Comment by eXpl0it3r** [comment]
Evtl. wäre ja Let's Encrypt auch eine Lösung.

**Comment by dbrgn** [comment]
Jep, sofern ihr Nginx Support inzwischen besser läuft :)

**Comment by lukasmartinelli** [comment]
> Any updates? :)

Ach ich muss es einfach machen. Ich habs immer rausgeschoben :grin:

**Comment by dbrgn** [comment]
Zertifikatswarnung wird immer noch angezeigt :)

**Comment by eXpl0it3r** [comment]
:grin:

**Comment by raphiz** [comment]
[Gemäss Heise Security](https://www.heise.de/newsticker/meldung/Admins-aufgepasst-SHA1-Zertifikate-vor-dem-endgueltigen-Aus-3460868.html) werden ab mitte Januar 2017 in allen Browsern richtige Fehlermeldungen angezeigt! 
Ich denke nebst der Umstellung auf Docker wird das bis Ende Jahr  knapp - evtl. wäre es kurzfristig einfacher (wohl oder übel) ein neues Zertifikat für 2 Jahre oder so zu Kaufen und anschliessend eine Let's Encrypt Migration anzupeilen.

**Comment by eXpl0it3r** [comment]
Knapp? Der Serveradmin muss einfach mal 30min Zeit investieren...

Ich würde es ja machen, aber der Zugriff will ja auch niemand rausgeben.

**Comment by fabianhauser** [comment]
Ja würde ich auch sagen, Let's Encrypt einzurichten ist nicht so eine Sache und einmal richtig eingerichtet wird das eh von alleine verlängert...

Ein guter Client ist IMO auch https://github.com/lukas2511/dehydrated, das macht aber keine automatischen nginx-restarts.

@saspeed Schauen wir das nächsten Montag beim [open\HSR Treffpunkt](https://www.openhsr.ch/community/#treffpunkt) kurz an? :wink:

**Comment by dbrgn** [comment]
Das Setup ist mit Ansible gemacht. Müsste einfach damit sauber einrichtbar sein, nicht einfach per SSH reinhacken :) Sonst ist's nicht gut reproduzierbar.

Ich habe mich zuletzt vor einem Jahr Let's Encrypt angesehen, da gab's folgende Probleme:

- Der offizielle Client war ziemlich gross und läuft als Root, sicherheitstechnisch ein wenig heikel
- Er hat Nginx nicht offiziell unterstützt. (Wir brauchen momentan Nginx wegen x-sendfile.)

Ist das inzwischen anders?

**Comment by eXpl0it3r** [comment]
> Müsste einfach damit sauber einrichtbar sein, nicht einfach per SSH reinhacken :) Sonst ist's nicht gut reproduzierbar.

Also ich hacke lieber mal ein valides Zertifikat hin, anstatt eine Seite für bald ein Jahr mit einer Zertifikat Warnung zu lassen...

* Seit dem es LE gibt, gab es alternative Clients, aber der offizielle Client braucht immer noch Root Access.
* Ich habe auf allen meinen Servern bis jetzt die Webroot Methode verwendet, die funktioniert solange der Webserver Dateien anbieten kann.

**Comment by dbrgn** [comment]
> Also ich hacke lieber mal ein valides Zertifikat hin, anstatt eine Seite für bald ein Jahr mit einer Zertifikat Warnung zu lassen...

Das einfachste wäre meiner Meinung nach, ein [4$ Cert](https://www.gogetssl.com/domain-validation/domain-ssl/) zu kaufen und das über das aktuelle Deployment zu installieren. Das ist in 10 Minuten gemacht. Und dann hat man 1 Jahr Zeit um ein sauberes Let's Encrypt Setup aufzusetzen. @saspeed @lukasmartinelli @raphiz was meint ihr?

@saspeed ist übrigens dran, die Entwicklung zusammen mit dem Open\HSR neu aufzugleisen.

**Comment by raphiz** [comment]
Mit einer Migration auf Docker muss das sowieso alles umgebaut werden. Da macht es für mich keinen Sinn jetzt zu viel Zeit zu Investieren (darum mein ursprünglicher Vorschlag). Ich schliesse mich da @dbrgn  an, für ein Jahr ein Zertifikat zu kaufen und die ganze Energie auf die Dockermigration zu investieren...Die 4$ bekommen wir scho zusammen :wink:

**Comment by dbrgn** [comment]
Ah, wusste gar nicht dass ihr Docker auch für die Produktion nutzen wollt, nicht nur für Dev :)

**Comment by lukasmartinelli** [comment]
> Mit einer Migration auf Docker muss das sowieso alles umgebaut werden. Da macht es für mich keinen Sinn jetzt zu viel Zeit zu Investieren (darum mein ursprünglicher Vorschlag). Ich schliesse mich da @dbrgn an, für ein Jahr ein Zertifikat zu kaufen und die ganze Energie auf die Dockermigration zu investieren...Die 4$ bekommen wir scho zusammen 😉

Das Studentenportal ist dann doch nicht ganz eifach vollständig zu dockerisieren weil vieles an den Ansible scripts hängt.

**Comment by dbrgn** [comment]
> Das Studentenportal ist dann doch nicht ganz eifach vollständig zu dockerisieren weil vieles an den Ansible scripts hängt.

Das macht nichts, du könnest sogar die Docker Images mit Ansible provisionieren :) Wobei ich in der Regel Dockerfiles bevorzuge.

**Comment by fabianhauser** [comment]
Wir haben soeben entschieden, dass ich als Übergangslösung im Dezember ein manuelles Let's Encrypt-Zertifikat erstelle; das Ziel ist es, im Februar den `nginx` mit Let's Encrypt zu Dockerisieren.
(Damit sparen wir uns auch die paar Franken für ein Zertifikat :wink:)

**Comment by fabianhauser** [comment]
![image](https://cloud.githubusercontent.com/assets/368799/21579436/7a2d6bb2-cfaf-11e6-852e-e51805f4bb8c.png)

Let's Encrypt ist mit [dehydrated](https://github.com/lukas2511/dehydrated) und automatischer Erneuerung direkt auf dem Server eingerichtet, aber **nicht** im automatischen Deployment, da wir beim nächsten Codesprint auf Docker umstellen wollen.

**Comment by dbrgn** [comment]
Cool, danke @fabianhauser!

**Comment by dbrgn** [comment]
@fabianhauser @raphiz gut sind wir gewechselt, RapidSSL ist extrem penetrant bei der customer retention 😆 

![img](https://tmp.dbrgn.ch/screenshots/20170511151848-imdbqtuv.png)

**Comment by fabianhauser** [comment]
Das macht ja einen sehr seriösen Eindruck 🙈
