### ISSUE TITLE
DNS Lookup schlägt fehl

### ISSUE THREAD

**Issue by DatenMetzgerX** [studentenportal/web#175]
```

nslookup studentenportal.ch
f;; connection timed out; no servers could be reached
```

Das selbe Problem besteht auch über online Dienste...
http://www.isitdownrightnow.com/studentenportal.ch.html 

Guets neus ;)

**Comment by dbrgn** [comment]
Wissen wir, der Grund ist, dass die DNS Server von Gib-Solutions (unserem Sponsor) down sind... Sind alle Kunden von ihnen betroffen, also sollte das wohl bald behoben sein!

**Comment by dbrgn** [comment]
Holy shit, whois für gib-solutions.ch und flashcable.ch gibt nichts zurück!

Auf Switch heisst es "diese Domain kann aktuell nicht registriert werden".

Konkurs sind sie nicht gemäss SHAB. Es gab zwar eine Mutation (https://www.shab.ch/shabforms/servlet/Search/1876387.pdf?EID=7&DOCID=1876387) aber that's all.

**Comment by dbrgn** [comment]
```
dig +short studentenportal.ch @dbrgn.ch
81.92.97.240
```

Jetzt nur noch herausfinden wie wir das bei Switch eintragen können...

**Comment by LePhil** [comment]
It's back.

**Comment by dbrgn** [comment]
Super! Ich versuche trotzdem noch die Kontrolle der Domain irgendwie zu kriegen. Am besten würde man @lukasmartinelli als technical contact eintragen. Dann könnten wir einen sekundären DNS eintragen.
