### ISSUE TITLE
Upgrade to Django 1.8 LTS

### ISSUE THREAD

**Issue by saspeed** [studentenportal/web#181]
For next month's first annual celebration of the official end of support for our currently used django 1.6 by the django project (which was April 1st last year), we should upgrade to django 1.8.11 (1.8 is considered an LTS release supported for another 2 years.) (see [Supported Versions](https://www.djangoproject.com/download#supported-versions)) 
While upgrading be aware of dependency issues related to required modules.
See #180 considering the tests as well.

**Comment by dbrgn** [comment]
The most tricky part is probably the switch in the migration system from django-south to django builtin migrations. Otherwise it should be fine.

**Comment by saspeed** [comment]
Thanks for the hint, I'm collecting more and more information about it
For future reference: 
http://stackoverflow.com/questions/29913612/upgrading-from-django-1-6-with-south-to-1-8-doesnt-modify-last-login-on-the
https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south
https://docs.djangoproject.com/en/1.8/ref/migration-operations/
https://docs.djangoproject.com/en/1.8/ref/migration-operations/

**Comment by The-Compiler** [comment]
Fixed via #193 - thanks @dbrgn!
