### ISSUE TITLE
Email-Versand funktioniert nicht

### ISSUE THREAD

**Issue by Elewyth** [studentenportal/web#184]
Die Aktivierungs-Email wurde nach 2 Wochen immer noch nicht versandt. Ebenfalls erhalte ich keine Email bei der Passwort Zurücksetzen-Funktion. Dies macht es mir leider unmöglich mich im Studentenportal anzumelden und Dateien runterzuladen.

Verwendete Benutzernamen bei der Registrierung:
1x mit metter
1x mit marc.etter
Bei beiden habe ich keine Aktivierungs-Mail und keine Passwort-Zurücksetzen-Mail erhalten. Bei dem Versuch sich neu zu registrieren, kommt die Fehlermeldung, dass der Benutzername bereits vergeben ist.

**Comment by dbrgn** [comment]
Kann ich bestätigen, Passwort-Recovery-Mail ist bei mir nicht eingetroffen.

Soweit ich mich erinnere ist auf dem Server ein eigener MTA eingerichtet, oder? Falls das Problem dort irgendwo liegt - ich kann https://www.sparkpost.com/ als Alternative empfehlen.

**Comment by dbrgn** [comment]
Habe es gerade mit @fabianhauser debuggt. Erstes Problem war, dass der DNS Server in resolv.conf nicht mehr funktionierte.

Wir können wegen der Firewall von Gib-Solutions keine externen DNS benutzen, aber wir haben dann die IP des neuen DNS gefunden.

Nun klappt aber SMTP o.ä. auf externe Mailserver nicht mehr, deshalb können Mails nicht zugestellt werden. Jemand müsste Gib-Solutions kontaktieren und fragen, ob an der Firewall etwas geändert wurde.

Am besten wäre es, den Server in die DMZ aufzunehmen, und die Firewall selber durch UFW zu managen.

Kontaktdaten zu Gib-Solutions kann ich gerne per Mail herausgeben.

**Comment by saspeed** [comment]
Hallo zusammen, 

Sorry, dass ich mich erst jetzt melde. 
@Elewyth Das Problem sollte am Wochenende behoben werden.
@dbrgn Ich melde mich per Mail bei dir.

**Comment by saspeed** [comment]
Nach Absprache mit unserem Hosting-Provider konnte das Problem behoben werden.
@Elewyth Das Registrieren sollte nun wieder problemlos funktionieren, bitte eröffne einen neuen Issue, falls dies nicht so ist.
