### ISSUE TITLE
Platform für Petitionen oder Umfragen

### ISSUE THREAD

**Issue by dns2utf8** [studentenportal/web#185]
Hallo zusammen

Wir würden gerne eine Petition/Umfrage machen. Können wir bis morgen (ja ja immerhin nicht bis gestern) eine kleine Umgebung machen?
Oder könnten wir spontan ein [LimeSurvey](https://www.limesurvey.org/de/) laufen lassen?

**Comment by eXpl0it3r** [comment]
Wer ist wir? Was für eine Umfrage? Wieso wird das hier gefragt?

**Comment by dns2utf8** [comment]
Wir = IT-Studenten
Umfrage = Das sollen die Studenten selber liefern können. Z.B. jemand sucht Gleichgesinnte um das Anliegen "3. Modulwahl" zu besprechen.
Hier = Ist von der HSR anerkannt, trotzdem flexibel.

**Comment by eXpl0it3r** [comment]
Also ist das ein Feature Request und das mit "morgen" ein Beispiel?

**Comment by dbrgn** [comment]
Ich glaube nicht, dass das Studentenportal der richtige Ort für sowas ist. Gibt ja genügend Tools die darauf spezialisiert sind :)

**Comment by dns2utf8** [comment]
"Morgen" wäre in diesem Fall wirklich der Donnerstag.
Welche Tools könnt ihr empfehlen?

**Comment by fabianhauser** [comment]
Da "Morgen" schon eine Weile her ist, und das Studentenportal dafür nicht wirklich der richtige Ort ist, schliesse ich das Issue mal :)
