### ISSUE TITLE
Registrierung kaputt?

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#186]
Ich habe versucht, mir sowohl mit `fbruhin` als auch mit `florian.bruhin` einen account zu klicken (vor einigen Wochen schon) - habe aber nie eine Mail gekriegt.

**Comment by dbrgn** [comment]
Siehe #184. Habe das Registrierungsmail nochmals ausgelöst, hast du es jetzt gekriegt? (Kann ev auch noch ein paar Minuten dauern...)

**Comment by The-Compiler** [comment]
Bisher ist mal nix angekommen...

**Comment by dbrgn** [comment]
Habe beide Profile gelöscht. Kannst du versuchen, dich erneut zu registrieren?

**Comment by The-Compiler** [comment]
Hat geklappt, danke!
