### ISSUE TITLE
Bad Gateway auf /tweets

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#187]
Wenn ich https://studentenportal.ch/tweets/ aufrufe, kriege ich einen 502 Bad Gateway von nginx.

![bad_gateway](https://cloud.githubusercontent.com/assets/625793/20089326/6ffd9f20-a586-11e6-8a66-598a9e4324f5.png)

**Comment by saspeed** [comment]
Danke für die Meldung, wir haben das Problem letzte Woche besprochen und arbeiten an einer Lösung.

**Comment by fabianhauser** [comment]
@The-Compiler das Problem ist nun nicht mehr Vorhanden, das Issue kann somit geschlossen werden :)
