### ISSUE TITLE
SHA1-Zertifikat

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#188]
https://studentenportal.ch/ braucht ein SHA1-Zertifikat, was als unsicher gilt, und von Chromium auch mit durchgestrichenem https und "This page is insecure (broken HTTPS)." angezeigt wird.

Im Januar 2017 wirds dann vermutlich gar nicht mehr funktionieren :wink:

Siehe auch https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know

**Comment by eXpl0it3r** [comment]
Siehe #170

**Comment by The-Compiler** [comment]
Ah, danke - hab nur nach SHA1 gesucht.
