### ISSUE TITLE
Docker development environment

### ISSUE THREAD

**Issue by saspeed** [studentenportal/web#189]
To improve development cycles and deployment stability we define a docker file for local development. 

Featuring:
* Full setup including postgresql & local mail pipe.
* Import of dummy data dump for local testing, and scenario validation.
* Installation manual.

Please reference this issue in pull requests.

**Comment by dbrgn** [comment]
> local mail pipe

I wouldn't do that. With the (currently configured) print-email-to-console backend you could simply use something like "docker logs -f" to watch them.

**Comment by raphiz** [comment]
Derzeit haben wir das Problem, dass die Images immer mit Root-Permissions eingehängt werden.
Wenn wir aber bereits im Dockerfile die Rechte Droppen, dann können wir die Berechtigungen nicht mehr updaten.
Postgres löst das Problem mit [Guso](https://github.com/tianon).

**Comment by fabianhauser** [comment]
Die Docker Umgebung ist fertig implementiert.

**Comment by dbrgn** [comment]
✨ congrats!
