### ISSUE TITLE
Sass Update

### ISSUE THREAD

**Issue by saspeed** [studentenportal/web#192]
Um das Projekt von gewissen Altlasten zu befreien.
Folgende dependencies möchten wir loswerden:
- Compass + Ruby durch pyscss ersetzen.

**Comment by raphiz** [comment]
Habe vorübergehend mal in 4f6f72d auf PyScss mit den Compass-Sass-Quellen migriert. Compass rauszufrickeln ist einfach zu viel Arbeit. Da würde ich ein komplettes Redesign machen.

**Comment by raphiz** [comment]
Pyscss kann auch die das meiste, wass compass kann. Ist alles im docker branch implementiert.
