### ISSUE TITLE
Kaputtes Profil / Profil löschen

### ISSUE THREAD

**Issue by Elewyth** [studentenportal/web#195]
Hallo

Ich habe letztes Jahr bereits den Issue #184 erfasst und dieser wurde behoben. Leider scheint mein Profil immer noch in einem "kaputten" Zustand zu sein. D.h.: Ich kann mich mit beiden Profilen nicht einloggen, habe nie eine Registrierungsmail erhalten und bei der Passwort-vergessen-Funktion erhalte ich ebenfalls keine Email. Bei #186 hat es funktioniert, indem die Profile manuell gelöscht und dann neu angelegt wurden. Könnte man meine Profile bitte auch löschen? Die verwendeten Benutzernamen waren metter und marc.etter.

Danke im Voraus :)

**Comment by fabianhauser** [comment]
@saspeed : Könntest du das mal anschauen? Merci!

**Comment by Elewyth** [comment]
Bump

**Comment by fabianhauser** [comment]
Hallo @Elewyth 

Ich habe deine Benutzer gelöscht, könntest du dich nochmals registrieren?

**Comment by Elewyth** [comment]
@fabianhauser entschuldige die (sehr) späte Antwort. Ich konnte mich registrieren, und alles funktioniert problemlos, danke!
