### ISSUE TITLE
Neue Dozenten

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#198]
[Stefan Richter](https://www.hsr.ch/Personenverzeichnis.1375.0.html?no_cache=1&L=0&tx_icscrm_pi4%5Bcontent%5D=4790&tx_icscrm_pi4%5Bid_person%5D=5013437) ist z.B. neu als Dozent an der HSR, aber im Studentenportal nicht zu finden.

**Comment by dbrgn** [comment]
Man müsste prüfen ob https://github.com/studentenportal/web/blob/master/apps/lecturers/management/commands/fetch_lecturers.py noch funktioniert.

Das Script kann folgendermassen aufgerufen werden:

    $ python manage.py fetch_lecturers --help

**Comment by The-Compiler** [comment]
Leider nicht - der login scheint fehlzuschlagen (auch wenn da ein HTTP 200 zurück kommt, und das Skript nix davon merkt), und die Seiten geben dann einen 404.

Wenn ich mir das HTML der Login-Seite anguck, braucht das irgendwas zum mit Typo3 das Passwort in JS zu verschlüsseln?

```html
<form action="HSR-intern-Anmeldung.4409.0.html?&amp;no_cache=1" target="_top" method="post" onsubmit="return TYPO3FrontendLoginFormRsaEncryption.submitForm(this, TYPO3FrontendLoginFormRsaEncryptionPublicKeyUrl);; return true;">
	<fieldset>
	<legend>Login</legend>
	<div>
		<label for="user">Benutzername:</label>
		<input type="text" id="user" name="user" value="">
	</div>
	<div>
		<label for="pass">Passwort:</label>
		<input type="password" id="pass" name="pass" value="">
	</div>

	

	<div>
		<input type="submit" name="submit" value="Login">
	</div>

	<div class="felogin-hidden">
		<input type="hidden" name="logintype" value="login">
		<input type="hidden" name="pid" value="4394">
		<input type="hidden" name="redirect_url" value="HSR-intern-Anmeldung.4409.0.html?&amp;no_cache=1">
		<input type="hidden" name="tx_felogin_pi1[noredirect]" value="0">
		
	</div>
	</fieldset>
```

Ich nehm an, das ist "neu"? Also wohl irgendwie den pubkey in Python kriegen und das crypto-Zeugs in Python neu implementieren, oder was nehmen, was JS kann... Beides nicht allzu spassig.

**Comment by dbrgn** [comment]
Alternativ könnte man versuchen, das LDAP anzuzapfen. Sicher eine nachhaltigere Lösung.

**Comment by fabianhauser** [comment]
Das ging wahrscheinlich mit dem Upgrade auf eine neue TYPO3 Version vor ca. einem Jahr kaputt. Soweit ich weiss, ist eine neue Webseite der HSR in Arbeit, es lohnt sich also vermutlich eh nicht, die `rsaauth` Extension von TYPO3 nachzuimplementieren...

**Comment by The-Compiler** [comment]
Ich glaube, `get_person_id` bräuchte kein Login, wenn es die öffentliche Suche nutzt - dann könnte man das csv auch einfach von Hand herunterladen und als Argument angeben.

**Comment by The-Compiler** [comment]
Alternativ könnte man doch auch die Abkürzung als Primary Key verwenden, das würde alles ein bisschen einfacher machen - oder? :wink:

**Comment by The-Compiler** [comment]
Mag jemand mindestens Hr. Richter von Hand hinzufügen? Ich hab schon 12 Zitate gesammelt, und andere Leute schmeissen nun schon Zitate von ihm bei Hr. Glatz rein...

**Comment by dbrgn** [comment]
Könnte ich machen, dafür bräuchte ich Name, Vorname, Kürzel und HSR-ID. Ich weiss nicht mehr genau was HSR-ID genau ist, aber Stolze hat z.B. die 533889.

**Comment by The-Compiler** [comment]
[Richter, Stefan, RIS und 5013437](https://www.hsr.ch/Personenverzeichnis.1375.0.html?no_cache=1&L=0&tx_icscrm_pi4%5Bcontent%5D=4790&tx_icscrm_pi4%5Bid_person%5D=5013437)

Magst du dann das oberste Zitat von 
https://studentenportal.ch/dozenten/173/ grad noch auf ihn migrieren, falls das einfach geht?

**Comment by dbrgn** [comment]
Done!

**Comment by The-Compiler** [comment]
Merci! Kanns sein, dass du HSR-ID und Kürzel vertauscht hast? Auf https://studentenportal.ch/dozenten/5013437/ steht nun "Kürzel: 5013437".

**Comment by dbrgn** [comment]
Whoops, zwei mal die ID eingetragen :) Danke, ist gefixt.

**Comment by Murthy10** [comment]
- Remove Import Script
- Add Form to add new Lecturer
