### ISSUE TITLE
Migration Server studentenportal.ch

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/web#199]
Da die Hardware des aktuellen studentenportal.ch-Servers langsam auf sein Lebensende zugeht, ist es an der Zeit, das Studentenportal auf einen neuen Server zu migrieren.
Die [Nine](https://nine.ch/) ist so freundliche und sponsert uns eine Root-VM!

Alle Ansible-issues wurden in https://github.com/studentenportal/deploy-new/issues ausgelagert.

Wir würden uns freuen, falls jemand Zeit hat, dabei zu helfen!

**Comment by dbrgn** [comment]
> Firewall (shorewall?)

Ich verwende jeweils ufw, das ist einfach zu administrieren und es gibt auch ein Ansible-Modul dafür.

**Comment by The-Compiler** [comment]
studentenportal.ch ist nun (endlich!) auf dem Server von Nine! :tada:
