### ISSUE TITLE
Partner-Logo

### ISSUE THREAD

**Issue by dbrgn** [studentenportal/web#201]
Gestern haben wir bei einer [Coredump](https://www.coredump.ch/)-Vorstandssitzung diskutiert, ob ihr eventuell Lust an einem Partner-Logo-Tausch auf der Website habt. Wir würden dann das Studentenportal links auf unserer Website als "Partner" verlinken, und ihr uns auf dem Studentenportal ebenso.

Falls Interesse besteht, könnte ich auch gleich einen PR machen.

**Comment by saspeed** [comment]
Einverstanden :+1: -> Logo bitte per Mail an team@studentenportal.ch

**Comment by dbrgn** [comment]
Geschickt :)

**Comment by dbrgn** [comment]
Ihr seid verlinkt, links unter der Navi: https://www.coredump.ch/

![screenshot](https://tmp.dbrgn.ch/sponsoren.png)

**Comment by dbrgn** [comment]
Ping! :)

**Comment by dbrgn** [comment]
Bump?

**Comment by dbrgn** [comment]
@fabianhauser falls ihr noch linktausch machen wollt: https://files.coredump.ch/logos/logo-v1.svg

Ansonsten -> close.
