### ISSUE TITLE
Automatische Dokumenten-Synchronisation mit Kitovu

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#206]
Wie einzelne von euch (mindestens @raphiz :laughing:) schon mitbekommen haben, bin ich zusammen mit @bytinbit und @ThunderKey momentan am HSR Engineering-Projekt. Wir entwickeln dazu ein Tool namens [kitovu](https://github.com/kitovu-bot/kitovu) welches ähnlich wie OpenHSR connect Dateien vom Skriptserver synchronisieren soll - jedoch nur auf die Synchronisation fokussiert, dafür mit GUI, tests, und basierend auf einer Plugin-Architektur.

WIr haben einen ersten Prototyp mit einem Skripteserver-Plugin, wollen aber gerne noch Moodle und/oder Studentenportal anbinden - hier solls vorallem um letzteres gehen.

Wenn ich mir #34 so anschaue, hat @dbrgn mal eine erste API implementiert, allerdings ohne Support für Dokumente, richtig? Habt ihr eine grobe Abschätzung, was es für einen Aufwand wäre, eine API für Dokumente zu implementieren, mit viel Python- aber wenig Django-Wissen?

Ausserdem wäre dann noch das Problem, dass man laut #34 bei @dbrgn API tokens kriegt - das würde dann vermutlich nicht mehr skalieren. Für eine erste Implementierung könnte man wohl im Webinterface einfach jeder Person ein API-Token anzeigen wenn eingeloggt, oder?

**Comment by dbrgn** [comment]
Wie ist denn der Plan, wollt ihr alle Dokumente direkt runtersyncen?

Das wäre dann nur unidirektional, d.h. Studentenportal -> Lokal, oder? Es wäre wohl gut wenn man in jeden Ordner auch noch ein README rein knallen würde, mit Link auf das Studentenportal, damit die Dokumente trotzdem noch bewertet werden können.

> Für eine erste Implementierung könnte man wohl im Webinterface einfach jeder Person ein API-Token anzeigen wenn eingeloggt, oder?

Das klingt eigentlich sinnvoll, ja.

> Habt ihr eine grobe Abschätzung, was es für einen Aufwand wäre, eine API für Dokumente zu implementieren, mit viel Python- aber wenig Django-Wissen?

Wichtig wäre mal ein Upgrade von Django auf eine supportete LTS-Version. Die aktuelle Version kriegt nichtmal mehr Security-Updates.

Die Implementation der Readonly-API wäre recht trivial. Man müsste nur einen Serializer konfigurieren, effektive Arbeit für jemanden der das Django REST Framework kennt wäre wohl unter einer Stunde. Einlesezeit wenn man Django / DRF noch nicht so kennt vielleicht ein paar Stunden.

**Comment by fabianhauser** [comment]
Ich finde die Idee von kitovu mit der Stundentenportal-Integration sehr cool! 🎉

Damit das Stundentenportal aber auch in Zukunft noch damit läuft, müssen wir einige Issues angehen:

Das Stundentenportal braucht ***dringend*** einen neuen Maintainer, damit hier endlich wieder was ins Rollen kommt.  
@saspeed, welcher seit einer Weile der Projekt-Leader ist, verspricht mir seit über einem Jahr, sich darum zu kümmern. Leider ist auch nach diversen Nachfragen (ausser weiteren Versprechen) nichts passiert...

@raphiz und ich waren auf der letzten VSHSR-GV, um auf die fehlende Aktivität bei diesem Projekt und dass das Stundenportal vermutlich nicht mehr lange "einfach so weiterläuft" hinzuweisen.  
Unser Vorschlag war es, einen Sponsor zu suchen, welcher z.B. mit Bountysource bountys auf wichtige Issues ausschreibt. Der VSHSR Vorstand wollte mal prüfen, was für Optionen sie haben, allerdings haben wir davon nichts mehr gehört.

Ein weiterer Vorschlag wäre es, einen Codesprint zu organisieren, um das längst überfällige Update und die Servermigration abzuschliessen (#181, #199). Der VSHSR (oder @openhsr) würde bestimmt 🍪/🍎/🍕/🍺  sponsoren. (Ich komme gerne mit der Servermigration helfen.)

**Comment by The-Compiler** [comment]
Hui, was hab ich denn hier angestossen :laughing: FWIW, ich wäre bei einem Sprint dabei. Hab wie gesagt nicht viel Ahnung von Django, aber kenne sicher Python und auch etwas Ansible und Serveradministration-foo.

Aber momentan hab ich halt mit dem EPJ (und [qutebrowser](https://www.qutebrowser.org/)) schon die Hände voll - wie sieht es denn aus, wenn rein hypothetisch jemand von uns eine File-API baut ohne sich (zumindest vor den Sommerferien) um die "technical debt" zu kümmern - würde jemand von euch davon ein review machen und gucken, dass das deployed wird? Oder ist momentan was deploying angeht eh schon jede Hoffnung verloren? :wink:

**Comment by fabianhauser** [comment]
@The-Compiler sorry, wollte dich nicht abschrecken, musste einfach mal deutlich festgestellt werden :wink:

Die Docker-Umgebung, die @raphiz und ich gemacht haben, sollte aber fürs Entwickeln gut und einfach brauchbar sein 🙂

Leider funktioniert das Deployment momentan nicht, da ein paar Abhängigkeiten nicht mehr online sind (weil es sie nicht mehr gibt oder sie hatten Cyber-Security-Löcher™️)...

**Comment by dbrgn** [comment]
Ich wäre bei einem Sprint auch dabei. Deployment sollte aber wenn möglich ein neuer Maintainer erledigen. Es bringt nichts wenn wir versuchen da irgendwas zu hotfixen wenn es beim nächsten Deployment wieder auseinanderfällt :)

**Comment by raphiz** [comment]
Ich kann mich euch nur anschliessen, ein neuer aktiver Maintainer wird dringend benötigt.. 
Habe gestern mit @mattbaumann gesprochen, er ist von Seiten VSHSR auch auf Maintainer-Suche.

**Comment by saspeed** [comment]
Wie @raphiz erwähnt hat, sind wir schon länger auf der Suche nach einem neuen Maintainer. 
Entsprechende Anfragen sind leider bisher negativ. Am vorgeschlagenen codesprint beteilige ich mich gerne.

**Comment by mattbaumann** [comment]
Wird dieser Issue noch gebraucht? Die API für das Synchronisieren sollte nach meinem Kenntnisstand schon vorhanden sein. Des Weiteren ist _Kitovu_ nicht ein _studentenportal.ch_ Problem 1. Grades und wenn ich die Liste der Issues ansehe wird dieser in Jahren noch nicht dran kommen.
Desweiteren sprengt ein weiteres _System_ den Rahmen der IT ziemlich, die schon jetzt sehr überlastet ist. Ich bitte darum auf die Korrektur / Stabilisierung des Vorhanden zu fokussieren und keine weitere _Fässer ohne Boden_ aufzureissen.

**Comment by The-Compiler** [comment]
Ja, es gibt nach wie vor keine API für die Dokumente. Den zweiten Abschnitt deines Kommentars ignoriere ich jetzt einfach mal.

**Comment by fabianhauser** [comment]
Wird Kitovu noch weiterenwickelt @The-Compiler?

**Comment by The-Compiler** [comment]
@fabianhauser Ich weiss von ein paar wenigen Leuten die es nutzen, wirklich weitergemacht haben wir daran bisher nicht. Ich kann mir aber gut vorstellen, dass @bytinbit, @ThunderKey und ich irgendwann mal wieder Lust und Zeit haben, daran was zu machen.

Unabhängig davon denke ich, dass es schon nützlich wäre, eine offizielle API zu haben, die auch Dokumente ausliefern kann - auch mit dem Ausblick, vielleicht in Zukunft mal bestehende Ablagen mit dem Studentenportal zu integrieren. Aber es existiert ja schon #34 für die API, drum mach ich das hier mal zu.
