### ISSUE TITLE
Codesprints FS2018

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/web#207]
Wie in #206 besprochen wäre es cool, wenn wir einen Codesprint durchführen könnten. Ich habe mir mal alles notiert, was mir dazu eingefallen ist an Vorbereitungen.

- [ ] Doodle erstellen für Datum/Zeitpunkt und an die Interessierten aus #206 senden
- [ ] Raum an der HSR reservieren (via VSHSR oder evtl. sfkeller)
- [ ] Mail versenden mit definitiver Doodle-Anmeldung an stud.i mit Termin via VSHSR
- [ ] Issues / Tasks vorbereiten (Aufteilen/Spezifizieren): #181, #199
- [ ] Essen
  - [ ] Finanzierung durch VSHSR oder @openhsr organisieren
  - [ ] 🍎, 🍪, 🍫, Chips einkaufen
  - [ ] 🍺
  - [ ] 🍕 (könnte an dem Abend nach Bedarf bestellt werden)
  - [ ] Teller, Servietten, Besteck (evtl. bei VSHSR / @openhsr vorhanden)

**Comment by dbrgn** [comment]
Übrignens, ich habe gerade gemerkt dass wir die Migration auf Django 1.8 bereits schonmal durchgeführt haben: https://github.com/studentenportal/web/pull/193 Es hat sich nur niemand die Mühe gemacht das zu testen :)

Von 1.8 auf 1.11 sollte nicht so ein Problem sein.

Django 1.11 LTS ist übrigens die letzte LTS-Version die Python 2 unterstützt. Vielleicht sollte man gleich versuchen, das Ganze auf Python 3 zu portieren.

**Comment by fabianhauser** [comment]
Hier der Link zum Doodle vom Studentenportal-Sprint: https://doodle.com/poll/ktihgvvh735yd7vh
Falls ihr weitere Terminvorschläge habt, immer her damit 😄

Wäre cool, wenn ihr (@The-Compiler, @bytinbit, @ThunderKey, @dbrgn, @saspeed, @mattbaumann, @raphiz) mal eintragen könntet, welche Termine in Frage kommen.

Wie gesagt ist das Ziel des Sprints 🍕🍻 , sowie den neuen Server fertig aufzusetzen, das Portal zu migrieren und auf eine neue Django-Version zu upgraden 😉

**Comment by fabianhauser** [comment]
@dbrgn Wenn ich mich richtig erinnere, hat nach dem Update nicht mehr alles 100% funktioniert (aber ist schon lange her, vielleicht habe ich das falsch im Kopf 🙈).

Wenn wir das ganze auf 1.11 heben, ist immerhin mal [bis 2020 alles im Grünen Bereich](https://www.djangoproject.com/download/), aber Python 3 wäre natürlich noch schöner 🙂

**Comment by thomase1993** [comment]
Kann man da auch mitmachen wenn man sich nur wenig mit python auskennt? Java finde ich immer uninteressanter für GUI-Anwendungen. Ev. könnt ihr jemand brauchen zum testen, tests schreiben, kaffee kochen :-)

**Comment by fabianhauser** [comment]
@thomase1993 auf jeden Fall, wir würden uns sehr über deine Hilfe freuen! Trag dich doch auch einfach ins Doodle ein :)

**Comment by dbrgn** [comment]
> Wenn ich mich richtig erinnere, hat nach dem Update nicht mehr alles 100% funktioniert

Klar, aber ich dachte dass das ein Maintainer testet und fertigstellt :wink: 

@thomase1993 kennst du dich ev. mit docker und ansible aus?

**Comment by thomase1993** [comment]
@dbrgn mit ansible noch nie gesehen aber ist ganz cool. Docker nur einmal auf meinem archlinux verwendet. Die Sprache von ansible scheint recht straight forward zu sein. Denke, dass kann aber schnell recht komplex werden, je nach Environment.

**Comment by dbrgn** [comment]
Kann man alles lernen :) Ansible ist nicht so schwierig.

**Comment by mattbaumann** [comment]
Hoi zäme
Ich habe meine freien Tage im Doodle eingetragen, könnt Ihr nochmals eine Nachricht auf diesem Thread versenden, damit ich weiss welches Datum dann fix ist.
Besten Dank und freue mich auf jeden, der kommt.
Matthias

**Comment by ThunderKey** [comment]
Hallo zusammen
Grundsätzlich wäre ich bei einem Codesprint dabei. Mir ist es jedoch unter dem Semester zu viel Stress zusätzlich zum Arbeiten, eigenen Projekten, Hobbies und dem Studium selbst. Für mich würden da nur die Semesterferien in Frage kommen.
Vielen Dank fürs Organisieren und Gruss,
Nicolas

**Comment by bytinbit** [comment]
ich schliesse mich Nicolas an: Unter dem Semester geht's mir nicht, auch wegen Arbeit/Studium/noch mehr Arbeit/noch mehr Studium.

**Comment by The-Compiler** [comment]
Sehe ich ein bisschen ähnlich - ich würd zwar sicher mal nen Abend unter dem Semester investieren, aber wahrscheinlich wird das dann auch nicht reichen, und das ganze versandet wieder. Von daher fänd ich nen Termin in den Sommerferien wo wir uns nen Tag Zeit nehmen können auch besser.

**Comment by dbrgn** [comment]
Ich wäre eigentlich froh wenn's mal an einem Nachmittag/Abend (z.B. ab 16:30 oder 17 Uhr) stattfinden würde. Bin kein Student mehr und habe keine Sommerferien. Und extra freinehmen dafür möchte ich auch lieber nicht :) Wenn man bis 22 Uhr daran arbeitet hat man so immerhin 5.5h Zeit.

**Comment by mattbaumann** [comment]
Ich schliesse mich am @dbrgn an. Ich brauche die Ferien für anderes, aber ich bin offen auch am Abend in den Ferien.

Grüsse
Matthias Baumann

**Comment by fabianhauser** [comment]
Aktueller Stand von diesem Issue:

@saspeed konnte zwei neue Administratoren für das Studentenportal ausfindig machen 🎉
Es macht Sinn, die beiden neuen Admins in einen Codesprint einzubeziehen, deshalb ist bisher nichts mehr gelaufen.

Wenn alles klappt, organisiert @saspeed zusammen mit dem @openhsr einen Codesprint diesen Sommer. Doodle sollte folgen.

**Comment by The-Compiler** [comment]
Wir hatten den Sprint nach der GV kurz angesprochen - vielleicht machts sogar Sinn, zwei Sprints zu machen?

- Erstmal einen Sprint unter einigen Leuten, die Python/Django/das Studentenportal schon gut kennen, um die schlimmsten Probleme zu lösen, damit das Ding wieder wartbar wird.
- Dann einen Sprint, bei dem wir auch Neulinge hinzuziehen können, und auch mit Mentoring/pair-programming sowohl das Studentenportal als hoffentlich auch die Neulinge weiterbringen können? Ich weiss da von mindestens zwei Personen an der HSR, die meinten, sie würden da schon gerne mal was beisteuern, aber halt nicht alleine.

**Comment by saspeed** [comment]
Los geht's! Um einen optimalen Termin für den nächsten Code Sprint zu finden, schlage ich folgende Termine vor: https://doodle.com/poll/g288626zi2atvkqz 
Treffpunkt an der HSR. Eingaben im Doodle bis zum Dienstag 12. Juni Mittag, werde ich berücksichtigen. 
Schwerpunkte des Code Sprints wird die Migration auf den neuen Server und das Django-Upgrade sein.

**Comment by saspeed** [comment]
Danke für eure Antworten! Ich möchte gleich zwei Termine setzen:

Wir treffen uns zum ersten Mal am **Donnerstag, 21. Juni um 18 Uhr an der HSR**.
Wie oben schon erwähnt, liegt beim ersten Treffen der Schwerpunkt auf dem Setup des neuen Servers und der Migration. Zu dokumentieren ist der neue Ablauf für CI (local testing, staging, release). Wir entscheiden an diesem Abend, ob der neue Server dann zum Production Server wird oder dies erst am 28. geschieht. 

Wir treffen uns zum zweiten Mal am **Donnerstag, 28. Juni um 18 Uhr an der HSR**. 
Spätestens an diesem zweiten Treffen setzen wir den neuen Server als Production Server. 
An diesem Treffen kümmern wir uns um Refactorings rund um das Upgrade auf Django 2.0+. 

Allfällige Vorarbeiten besprechen wir bilateral bzw. in den jeweiligen Issues.

**Comment by fabianhauser** [comment]
Habe für den ersten Codesprint die Docker-Umgebung noch etwas aufpoliert/umgebaut, siehe #209.

Ich hatte gehofft, dass ich es auch heute noch an den Sprint schaffe, das wird aber leider nicht klappen.

Auf Basis von der Docker-Umgebung kann jetzt das Django Update (#193) und einrichten von Ansible in #199 angegangen werden.

**Comment by dbrgn** [comment]
Danke @fabianhauser :)

Ich mache mich gleich auf den weg, muss aber aus Temperaturregulierungsgründen noch kurz in den See springen. Komme ev ein paar Minuten verspätet :slightly_smiling_face:

**Comment by mattbaumann** [comment]
Hoi zäme
Wir haben beim letzten codesprint mal pro forma abgemacht, dass wir einen weiteres Datum organisieren. Ich möchte deshalb in die Runde fragen, ob dies noch immer aktuell ist und Interesse dazu besteht?
@mattbaumann und @fabianhauser stellen uns vor, dass @thomase1993 @ThunderKey ab diesem Datum dann das Projekt übernehmen und deshalb dann auch dabei sein sollten.
Viel Erfolg bei den Prüfungen!

**Comment by thomase1993** [comment]
Danke für das Vertrauen. Ich hab keine Erfahrungen mit Python, Package-Managern wie sie in java, Python usw. verwendet werden, OR-Mappern, der Python-IDEs und den Virtualisierungslösungen wie Docker u.ä. 

Ich hab mich zum Code-Sprint nicht angemeldet, da ich mit dem Studium + Arbeitsplatz ein wenig über- bzw. gefordert bin. Nächstes Semester habe ich zusätzlich noch das Engineering-Projekt.

Wenn ich dabei bin, will ich voll dabei sein und alles was ich verspreche dann auch einhalten (Deadline, Umsetzungen usw.). Das kann ich derzeit leider nicht garantieren. Deshalb werde ich nicht daran teilnehmen können.

**Comment by The-Compiler** [comment]
> Wir haben beim letzten codesprint mal pro forma abgemacht, dass wir einen weiteres Datum organisieren. Ich möchte deshalb in die Runde fragen, ob dies noch immer aktuell ist und Interesse dazu besteht?

Ja, nach den Prüfungen, wie damals afaik abgemacht.

**Comment by ThunderKey** [comment]
@mattbaumann Ich glaube da haben wir uns falsch verstanden. Ich habe keine Kapazität um das Projekt zu übernehmen.

Bei einem Codesprint wäre ich sicherlich dabei wenn es zeitlich aufgeht, aber mehr liegt bei mir leider nicht drin.
