### ISSUE TITLE
Prüfungen auch ohne Login bereitstellen

### ISSUE THREAD

**Issue by bugybunny** [studentenportal/web#208]
Tl;dr `Soll man dieses Dokument ohne Login downloaden können?` soll für die MSE Module (oder sogar generell) auch für Prüfungen bereitstehen.

Die Checkbox `Soll man dieses Dokument ohne Login downloaden können?` steht für alle Typen ausser Prüfungen zur Verfügung. Ich gehe stark davon aus, dass das schon Sinn macht, dass Prüfungen wirklich nur HSR Studenten zur Verfügung gestellt werden dürfen (oder ist das kein Müssen sondern nur ein Können?

Das Studentenportal unterstützt auch die MSE-Module und während meines Studiums habe ich einfach alles was ich hatte auch aufs Studentenportal geladen, da ich das viel besser finde für nachfolgende Generationen als Dropbox-Ordner die allenfalls verloren gehen. Nun ist es beim MSE so, dass dieser von mehreren Hochschulen der Schweiz ist. Eben habe ich eine E-Mail von einem ZHAW-Student bekommen, der gerne ein Prüfung herunterladen würde. Ich habe sie ihm einfach mal per E-Mail geschickt. Ich kann mir vorstellen, dass das noch häufiger geschehen wird in Zukunft, andererseits weiss ich aber auch nicht, wie bekannt das Studentenportal bei Nicht-HSR-Studenten ist.

Jedenfalls wäre es deshalb super, wenn ich die Prüfungen für die MSE-Module auch ohne Login zur Verfügung stellen könnte. Da ich diese Prüfungen einfach als etwas anderes flaggen könnte und diese dann allen zur Verfügung stehen, könnte man das ja gleich für alle Module machen, oder? Oder gibt das rechtliche Probleme?

**Comment by dbrgn** [comment]
Die ideale Lösung hierfür wäre #116.

**Comment by fabianhauser** [comment]
Closing in favour of #116
