### ISSUE TITLE
Postgres citext extension via Migration installieren

### ISSUE THREAD

**Issue by dbrgn** [studentenportal/web#210]
Depends on #193

**Comment by dbrgn** [comment]
Might already be solved in #193 migrations!

**Comment by The-Compiler** [comment]
I rebuilt my postgres docker image and got this indeed:

```
E   ProgrammingError: type "citext" does not exist
E   LINE 1: ...tegory" ("id" serial NOT NULL PRIMARY KEY, "name" CITEXT NOT...
```

I didn't try running `manage.py migrate` at that point though.

**Comment by dbrgn** [comment]
> Might already be solved in #193 migrations!

It wasn't added to a migration so far :slightly_smiling_face: 

You'll have to run `CREATE EXTENSION IF NOT EXISTS citext;` in PostgreSQL. This is also part of the deploy/test/start.sh and deploy/test/dev.sh scripts.

A way to solve this in a better way would be to add a migration called `0000_setup.py` in the `front` app that runs the command above in raw SQL. Then ensure that the migration `0001_initial.py` as well as all initial migrations in other apps depend on that migration.

**Comment by The-Compiler** [comment]
Alright! Not going to do that as part of my current upgrade work most likely, time is tight enough already :laughing:

**Comment by Murthy10** [comment]
Had quite a raw time doing so and ran into several errors until I found the following explanation:

> Due to limitations of Django's dynamic dependency feature for swappable models, the model referenced by AUTH_USER_MODEL must be created in the first migration of its app (usually called 0001_initial); otherwise, you'll have dependency issues.
