### ISSUE TITLE
Komme nicht auf euer Portal

### ISSUE THREAD

**Issue by PhilProgramm** [studentenportal/web#214]
Liebes Team
Ich komme leider nicht auf euer Portal mit meinem Namen "pwilli". Wenn ich versuche einen Account zu erstellen, erhalte ich keine Aktivierungs-E-Mail.
Der Grund ist wahrscheinlich, dass es schon mal einen pwilli an der HSR gegeben hat.
Meine E-Mail-Adresse lautet: philippe.willi@hsr.ch

Könnt ihr bitte meinen Account erstellen mit dieser Adresse oder den alten meines Vorgängers löschen, damit ich einen erstellen kann?

Vielen Dank und Gruss
Phil

**Comment by The-Compiler** [comment]
Ich hab keinen Zugriff auf den Server - aber kannst du versuchen, mit philippe.willi einen Account zu erstellen?

**Comment by PhilProgramm** [comment]
Cool das hat geklappt! Vielen Dank :)
