### ISSUE TITLE
Netsparker / Security Tools / Mail-Flut

### ISSUE THREAD

**Issue by dbrgn** [studentenportal/web#221]
Hoi zäme

Lässt jemand von euch @studentenportal/maintainers einen Netsparker-Scan auf das Studentenportal laufen?

Ich habe schon etwa 6000 Mails gekriegt :roll_eyes: Da muss man sich nicht wundern, wenn der Studentenportal-Mailserver irgendwann auf einer Blacklist landet :wink: Die Datenbank wird natürlich auch zugespammt.

![img](https://tmp.dbrgn.ch/screenshots/20191020111434-u6kni0f0.png)

Falls das jemand von euch ist, bitte wieder deaktivieren. Wenn ihr etwas für die Security tun wollt, sollte man einfach mal alle Dependencies updaten.

Cheers, Danilo

**Comment by dbrgn** [comment]
...und wieder 1800 Mails.

**Comment by fabianhauser** [comment]
Also ich auf jeden Fall nicht.
Habe mal das Studentenportal-Postfach eingetragen, damit dort die Mails auf jeden Fall auch reinkommen...

**Comment by dbrgn** [comment]
Mutig :joy:

Am besten würde man das Melde-Formular nur mit Login zugänglich machen. Dann wäre das Problem gelöst (falls niemand von euch den Scanner gestartet hat).

**Comment by fabianhauser** [comment]
Hab gerade mal noch die Mail-Queue geleert, da waren noch etwa 100'000 Mails hängig an dich @dbrgn 😉

**Comment by dbrgn** [comment]
:joy: :joy: danke! Hab's gemerkt, da kamen immer wieder so 1000er chunks rein :see_no_evil:

**Comment by fabianhauser** [comment]
Denke, es macht Sinn, wenn wir hier ein Captcha einbauen? Auch externe sollten ja Dokumente melden können, wenn ein Dokument rechte verletzt.

**Comment by dbrgn** [comment]
Wäre cool wenn es ohne ReCAPTCHA gehen würde, das nervt echt unglaublich.

Ich denke falls jemand Rechteverletzung melden möchte, kann man das via Kontaktadresse / E-Mail tun. Hat's bisher erst einmal gegeben, wegen Pflanzenfotos.

**Comment by fabianhauser** [comment]
> Ich denke falls jemand Rechteverletzung melden möchte, kann man das via Kontaktadresse / E-Mail tun.

Okay, das geht natürlich auch. Obwohl ich dann nicht ganz den Mehrwert vom Meldeformular im Allgemeinen sehe 😄

**Comment by dbrgn** [comment]
Da ging's mehr um inhaltliche Fehler oder zB veraltete Zusammenfassungen die nicht mehr zum aktuellen Stoff passen :)

**Comment by The-Compiler** [comment]
Zwei weitere Möglichkeiten, die mir so durch den Kopf schwirren:

- Eine Mischung aus beiden Vorschlägen: Report-Formular ohne Captcha wenn eingeloggt, aber mit Captcha wenn ohne Login darauf zugegriffen wird. Sollte aus meiner Sicht kaum einen Mehraufwand darstellen verglichen mit dem Einbau des Captchas.
- Das Report-Formular komplett entfernen. Wie oft wird/wurde das denn gebraucht? Wenns um inhaltliche Fehler und veraltete Zusammenfassungen geht, ist das wirklich die Aufgabe der Studentenportal-Admins, sich darum zu kümmern? Reicht da Datum/Bewertung nicht schon als Signal dafür aus?

Was meint ihr?

**Comment by fabianhauser** [comment]
Denke, es reicht, das Formular zu entfernen und evtl. etwas prominenter auf die Kontakt-Adresse hinzuweisen.

Hat aber IMO keine hohe Priorität - seit diesem Vorfall hatten wir keine Probleme mehr damit.

**Comment by The-Compiler** [comment]
Wir haben uns entschieden, das Formular zu entfernen. Hier ist der Commit wo's implementiert wurde: 3ae6868e1f25d93363fa69839125b09c0460947c

**Comment by The-Compiler** [comment]
Hab's hier rausgeschmissen: 34409a10f11c928b126b88fe5798fd2dbbce8313

Werd ich dann mergen, nachdem das Django/Python-Upgrade drin ist.
