### ISSUE TITLE
AUTHORS.txt aktualisieren

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#227]
AUTHORS.txt sagt momentan:

```
Maintainers
-----------

Danilo Bargen @dbrgn
Lukas Martinelli @lukasmartinelli

Contributors
------------

Fabian Vogler @fabian
Peter Manser @petermanser
Michi Gysel @theScythe
```

Da sollten vermutlich noch einige Contributors mehr rein, und die Maintainer stimmen wohl auch nicht mehr so ganz. Vielleicht macht's eher Sinn, da @fabianhauser reinzunehmen (ggf. mich, ggf. @dbrgn @lukasmartinelli). Was meint ihr?

**Comment by dbrgn** [comment]
Oder rausnehmen und https://github.com/studentenportal/web/graphs/contributors verlinken, dann muss man das File nicht up to date halten :)

**Comment by fabianhauser** [comment]
Den Vorschlag von Danilo mit den GitHub-Contributers finde ich gut - dann müssen wir die Datei nicht andauernd aktualisieren.

Falls wir irgendwo eine Kontakt- bzw. Admin-E-Mail brauchen, würde ich immer team@studentenportal.ch nehmen.

**Comment by The-Compiler** [comment]
Hab in bb68e7db9c5cb4d398af753e3a1fe00061a102e9 das File entfernt und dafür was ins README getan - werd ich ebenfalls nach dem fetten Upgrade dann mergen.
