### ISSUE TITLE
Autoformatter nutzen

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#228]
Es gibt inzwischen einige auto-formatting-Tools, die ziemlich weit verbreitet sind. Vielleicht macht's auch Sinn, sowas für das Studentenportal zu nutzen?

Spontan fallen mir ein:

- [black](https://github.com/psf/black) (wird z.B. auch von Django genutzt)
- [isort](https://github.com/timothycrosley/isort)
- [pyupgrade](https://github.com/asottile/pyupgrade) (eher einfach einmalig um 3.6-Syntax zu verwenden, siehe #225)
- [yapf](https://github.com/google/yapf) (vermutlich eher nicht, black hat ne deutlich grössere Community)
- [autopep8](https://github.com/hhatto/autopep8) (dito)
- [autoflake](https://github.com/myint/autoflake)

Falls es keine Einwände gibt, pushe ich mal nen Commit, der black + isort über die ganze Codebase lässt. Die anderen Tools kann man sich dann ja bei Gelegenheit mal genauer anschauen.

**Comment by Murthy10** [comment]
@The-Compiler hast du black + isort über die Codebase laufen lassen? 
Falls nicht, kann ich dies gern noch nachholen. 

Ist immer noch black + isort gewünscht? @fabianhauser @dbrgn

**Comment by fabianhauser** [comment]
Auf jeden Fall `black`, `isort` ist vermutlich auch ok (ich habe mit `isort` in einem Edge-Case mal schlechte Erfahrungen gemacht - das sollte für das Studentenportal aber kein Problem sein). (Kannst du ja einfach mal machen @Murthy10, allenfalls ändert sich einfach nix.)

`pyupgrade` mal auszuführen würde vermutlich auch Sinn machen.

`black`, `isort`, `autoflake` sollten dann auch in einem Check-Modus ins CI (und irgendwo in Contributor Guidlines, damit man nicht alles aus dem CI herauserahnen muss.)
