### ISSUE TITLE
Upgrades von Dependencies

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#229]
Kurze Übersicht (primär für mich selbst), welche Dependency-Upgrades ausser Django selbst noch anstehen:

# Tests

- [x] pytest 4.1 -> 4.6
- [x] pytest 4.6 -> 5.3 (unterstützt nur noch Python 3)
- [x] coverage 4.3.4 -> 4.5.4
- [x] coverage 4.5.4 -> 5.0.3 (`sed` in `.travis.yml` funktioniert nicht, da `.coverage` eine sqlite-Datenbank ist. Vermutlich hilft die `[run] relative_files = True`-Option.)
- [x] six 1.10 -> 1.14 (kann vermutlich rausgeschmissen werden, sobald nur noch Python 3 unterstützt wird)
- [x] pytest-django 3.4 -> 3.8
- [x] pytest-cov 2.5 -> 2.8
- [x] mock 1.0.1 -> 3.0.5
- [x] coveralls 1.1 -> 1.10.0
- [x] model_mommy [ersetzen durch](https://model-bakery.readthedocs.io/en/latest/migrating_from_mommy.html) model-bakery

# Local

- [x] django-debug-toolbar 1.9 -> 1.11
- [x] django-debug-toolbar 1.11 -> 2.1 (erst möglich nachdem `MIDDLEWARE_CLASSES` ersetzt wird, also wohl nach dem Upgrade auf Django 2.0)

# Production

- [x] gunicorn 0.17.4 -> 20.0.4
- [x] newrelic 2.6.0.5 -> 5.4.1.134 (aber siehe #191)

# Base

- [x] Pillow 2.6.1 -> 7.0.0 (wird nur indirekt gebraucht, also entfernt)
- [x] django-extensions (wird gar nicht gebraucht, also entfernt)
- [x] psycopg2 2.7.5 -> 2.8.4
- [x] Unipath 1.0 -> 1.1
- [x] Unipath ersetzen durch pathlib.Path (nach Upgrade auf Python 3)
- [x] python-dateutil 2.6.0 -> 2.8.1
- [x] django-messagegroups 0.4.3 -> 0.4.5
- [x] django-registration-redux 1.9 -> 2.5
- [x] django-registration-redux 2.5 -> 2.7 (seems to break a test, see commit message)
- [x] django-sendfile 0.3.4 -> 0.3.11 (ev. Alternativen suchen, Projekt scheint tot zu sein)
- [x] django-dajaxice-ng muss raus, siehe #215 
- [x] django-model-utils 1.3.1 -> 3.2.0
- [x] django-model-utils 3.2.0 -> 4.0.0 (kein Django 1.11-Support mehr)
- [x] django_compressor 1.5 -> 2.4
- [x] django-mathfilters 0.1.3 -> 0.4.0
- [x] easy-thumbnails 2.5 -> 2.6
- [x] easy-thumbnails 2.6 -> 2.7 (kein Python 2-Support mehr)
- [x] pyScss 1.3.5 ist aktuell
- [x] beautifulsoup4 4.3.2 -> 4.8.2
- [x] requests 1.2.3 -> 2.22.0
- [x] vobject 0.8.2 -> 0.9.6.1
- [x] djangorestframework 3.6 -> 3.9
- [x] djangorestframework 3.9 -> 3.11 (kein Python 2-Support mehr)
- [x] tweepy 2.2 -> 3.8.0

**Comment by The-Compiler** [comment]
So, nun fehlen nur noch `gunicorn` und `newrelic` aus den production requirements - @fabianhauser werden die dann beim neuen Deployment auch noch so gebraucht (aus dem requirements-file) oder kann ich mir die Arbeit sparen?

**Comment by fabianhauser** [comment]
`newrelic` wird z.Z. eh nicht verwendet, so viel ich weiss - kann also raus.

Betr. `gunicorn`: glaube der ist für WSGI applikationen immer noch ein bisschen der Platzhirsch.
Von dem her wird der vermutlich weiter genutzt.

**Comment by The-Compiler** [comment]
Okay, newrelic ist schon seit https://github.com/studentenportal/deploy/commit/f01fc0e4d628bf54f7c836b4c8e32d5d30c602ae draussen. Ich nehm das mal raus.

Zu gunicorn hab ich mal etwas https://github.com/studentenportal/deploy-new/pull/29/ angeguckt - dort wird ja Traefik benutzt. Wenn ich das richtig verstehe, würde dann Traefik direkt mit Gunicorn interagieren, und nginx wär nur noch für statische Files da. Keine Ahnung inwiefern das dann in der Praxis funktioniert, insbesondere wegen `django-sendfile`.

@fabianhauser Ich glaub wir sitzen uns dann am besten mal zusammen und gucken uns das gewünschte Deployment genauer an.

**Comment by The-Compiler** [comment]
So, sobald 863e6ad58407ced28cdfe63a2b1b8bcd4e698b38 drin ist, ist auch hier alles erledigt. Hab Gunicorn jetzt einfach mal aktualisiert, scheint gemäss nem kurzen Test immer noch so zu funktionieren wie vorher.

**Comment by dbrgn** [comment]
gunicorn ist eine sehr unkomplizierte Dependency, die machen einfach die "Übersetzung" von HTTP auf WSGI. Kann man problemlos hinter Traefik oder Nginx setzen.

Für bessere Performance gibt's noch uWSGI (https://uwsgi-docs.readthedocs.io/en/latest/), Server wie Nginx können dann über ein Binärprotokoll damit kommunizieren, welches weniger Overhead hat als HTTP. Ist aber für's Studentenportal sicher Overkill und macht Debugging schwieriger.
