### ISSUE TITLE
Handhabung von Pinning in requirements-Dateien

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#230]
Momentan haben wir eine Mischung aus drei verschiedenen Versions-Pinnings:

- Kein Pinning (`django-extensions`)
- Pinning auf die Minor-Version (`pytest>=4.6,<5`)
- Pinning auf die exakte Version (`Pillow==2.6.1`)

Sobald die Dependencies mal soweit aktualisiert sind, sollten wir das vermutlich vereinheitlichen.

Es bietet sich dann wohl auch an, nen Service zu verwenden, der jeweils PRs aufmacht mit Dependency-Upgrades. Ich kenne da:

- [Dependabot](https://dependabot.com/) - gehört zu GitHub inzwischen, hat bei mir mit qutebrowser aber nach einem Pipfile (für [pipenv](https://pipenv.kennethreitz.org/en/latest/)) verlangt. Von pipenv halte ich persönlich nicht viel.
- [pyup.io](https://pyup.io/) - hat lange gut bei qutebrowser funktioniert, macht aber auf einmal keine PRs mehr auf seit ein paar Monaten und es scheint keinen Support zu geben.
- [requires.io](https://requires.io/) - relativ spartanisch, aber tut was es soll, und das soweit zuverlässig.

**Comment by Murthy10** [comment]
@The-Compiler @fabianhauser  was sollte hier unternommen werden?

Pinning noch auf exakte Versionen setzen?
Und Dependabot "einrichten" ? Denke sollte auch mit pip funktionieren.

**Comment by fabianhauser** [comment]
@Murthy10 👍

**Comment by Murthy10** [comment]
Dependabot -> is this sufficient? https://github.com/studentenportal/web/settings/security_analysis

**Comment by fabianhauser** [comment]
@Murthy10 these settings only concern security updates AFAIK.
Dependabot is now integrated into GitHub Actions, see [this documentation page](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates). I'd suggest to limit non-security updates to biweekly tough.

**Comment by fabianhauser** [comment]
Resolved with #284
