### ISSUE TITLE
DocumentDownloads logging

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#231]
Momentan werden alle Downloads inklusive der vollen IP des Downloaders gespeichert. Wirklich benötigt wird aber eigentlich nur ein Download-Count.

Macht's wirklich Sinn, diese Informationen abzuspeichern?

Zumindest laut DSGVO [gelten IP-Adressen](https://www.ctrl.blog/entry/gdpr-web-server-logs.html) als personenbezogene Daten, weiss jetzt nicht wie's in der Schweiz aussieht. Und selbst wenn's rechtlich erlaubt wäre, ists IMHO wegen Datensparsamkeit nicht grad sinnvoll.

Falls es wirklich nen guten Grund gibt (abuse?), dann sollten immerhin die IPs nach 48h oder so entfernt werden, oder?

**Comment by fabianhauser** [comment]
IMO brauchen wir die IP-Adresse der Downloads nicht zu speichern...

**Comment by dbrgn** [comment]
Ich glaube das war mal für Download-Count-Deduplizierung oder Abuse gedacht. Kann sicher weg.

**Comment by The-Compiler** [comment]
Hab die IP in 1b817b28da2879bdfa52857bcbbd187e90c9f182 rausgeschmissen - werd ich ebenfalls nach dem fetten Upgrade dann mergen.
