### ISSUE TITLE
"Tipps zum Studium" entfernen?

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#232]
TIL: Das Studentenportal hat eine ["Tipps zum Studium"](https://studentenportal.ch/tipps/)-Seite!

Der Menüpunkt dazu wurde in c69f7d59f9627ce20e0760123332ad32019a98dc auskommentiert, aber die Seite an sich existiert noch.

Nachdem das in den letzten 6 Jahren wohl niemand vermisst hat, kann die wohl ganz weg?

**Comment by dbrgn** [comment]
Das ist eine 1:1 Kopie vom ur-alten PHP-Studentenportal, das kann wohl weg :slightly_smiling_face:

**Comment by The-Compiler** [comment]
Another hidden gem: Die ["Statistiken"-Seite](https://studentenportal.ch/statistiken/). Die find ich aber irgendwie noch lustig.

**Comment by dbrgn** [comment]
Die würde ich wenn möglich reaktivieren :smile: Natürlich nur mit Login.

Hier waren noch ein paar weitere Statistik-Ideen: https://github.com/studentenportal/web/issues/97

**Comment by The-Compiler** [comment]
Okay, dann mach ich das hier mal zu wenn die Tipps-Seite entfernt ist, und wir tracken die Statistik-Seite als Teil von #97.
