### ISSUE TITLE
Basic Auth für API

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#234]
Gibt's einen Grund, dass die DRF API kein Basic Auth erlaubt? Würde es gerne einschalten, weil's dann deutlich einfacher ist, mit der API rumzuspielen.

**Comment by dbrgn** [comment]
Mit User/Passwort? Kann man machen, man muss einfach aufpassen dass die Berechtigungen mit jenen übereinstimmen, die man hat wenn man als normaler User die Website benutzt.

Das würde dann auch Apps ermöglichen, die im Namen des jeweiligen Users Zitate posten können, etc.

**Comment by The-Compiler** [comment]
> Mit User/Passwort? Kann man machen, man muss einfach aufpassen dass die Berechtigungen mit jenen übereinstimmen, die man hat wenn man als normaler User die Website benutzt.

Momentan ist ja nur Session Authentication (also mit der bestehenden Login-Session) erlaubt. Da hat man ja schon dasselbe Problem, dass die API dann nix erlauben darf, was man nicht sonst schon könnte. Der einzige Unterschied wäre, dass halt auch HTTP Basic Auth mit Username/Passwort statt mit Login-Formular und Session-Cookie erlaubt ist.

**Comment by dbrgn** [comment]
Achso, ich dachte es gäbe Static API tokens oder so? Session Auth ist nur nützlich zum Testen (via Webinterface).

**Comment by The-Compiler** [comment]
> Achso, ich dachte es gäbe Static API tokens oder so?

Ne, momentan ist nur session auth drin:

https://github.com/studentenportal/web/blob/0fef034521b9c8fe1ac00421190fd4096e905e96/config/settings.py#L302-L304

> Session Auth ist nur nützlich zum Testen (via Webinterface).

Und für AJAX!
