### ISSUE TITLE
Star rating code vereinheitlichen

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#235]
Bisher wird Dajaxice (bzw. neu DRF) für das Rating von Dozenten benutzt, aber jQuery und eine eigene DocumentRate view für das Rating von Dokumenten.

Vermutlich würd's Sinn machen, die zwei Dinge etwas zu vereinheitlichen um weniger Code zu duplizieren.

**Comment by fabianhauser** [comment]
Resolved with #313
