### ISSUE TITLE
Handhabung von Tests mit Twitter-Token

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#236]
Momentan schlägt ein Test fehl, wenn kein Twitter Token gesetzt wurde:

```
______________________________ TweetListTest.test_tweet_display ______________________________
tests/tweets/test_views.py:48: in test_tweet_display
    assert len(response.context['tweets']) == 3
E   AssertionError: assert 0 == 3
E    +  where 0 = len([])
------------------------------------- Captured log call --------------------------------------
ERROR    apps.tweets.views:views.py:28 You need to set TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET env variables!
```

Der sollte vermutlich eher einfach übersprungen werden.

Ausserdem sagt `development.md`:

> Wenn du die Twitter Einbindung nutzen willst, musst du im Twitter Developer
Center eine App erstellen

Aber die API keys in `deploy/dev/test.sh` sind ja eh schon public und funktionieren. Kann man also einfach die verwenden, und falls nicht, warum sind sie dann public?

**Comment by fabianhauser** [comment]
> Aber die API keys in `deploy/dev/test.sh` sind ja eh schon public und funktionieren. Kann man also einfach die verwenden, und falls nicht, warum sind sie dann public?

Hmm, ich habe ehrlich gesagt gerade keine Ahnung, was das für Tokens sind.

Würde den Test überspringen, glaube eh nicht, dass viele Leute sich die Tweets der Integration anschauen... (evtl. könnten wir die integration auch rausschmeissen? IMO bietet das nicht (mehr) viel mehrwert.)

**Comment by The-Compiler** [comment]
`TWITTER_ACCESS_KEY` und `TWITTER_ACCESS_SECRET` scheinen abgelaufen/revoked zu sein. Mit `TWITTER_CONSUMER_KEY` und `TWITTER_CONSUMER_SECRET` kann ich der App "VSHSR Studentenportal Test" Zugriff auf meinen Twitter-Account geben.

@dbrgn War das :+1: oben auch für den Teil "Twitter-Integration rausschmeissen" gedacht? Falls ja, dann mach ich das gleich zusammen mit dem Report-Formular (weniger Code, yay!)

**Comment by dbrgn** [comment]
Jep, denke die Integration bringt recht wenig Mehrwert :)

**Comment by The-Compiler** [comment]
Hab's hier rausgeschmissen: f8a223251e621ff5f8bdcaea6f410eeca878096a

Werd ich dann mergen, nachdem das Django/Python-Upgrade drin ist.
