### ISSUE TITLE
Pillow-Dependency: Nicht gebraucht?

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#238]
Pillow kam (ursprünglich als PIL) in e93b4da965676e0e5e5db7fdbaf512b5fca4a5fa dazu (Oktober 2011). Es wurde dann ab und zu auch aktualisiert (und schlussendlich zu Pillow migriert).

Ich sehe aber keinen Ort in der Codebase, wo PIL/Pillow wirklich genutzt wird. Es wird wohl indirekt via `easy-thumbnails` genutzt, aber wir haben bisher in `requirements.txt` sonst keine indirekten Dependencies dabei - und easy-thumbnails kam erst ein Jahr nach PIL dazu (11824b0646ca1ccb649820f00f5365cb7fa82c39, Oktober 2012).

@dbrgn Hast du ne Ahnung, warum Pillow ne Dependency ist? Übersehe ich irgendwo etwas?

**Comment by dbrgn** [comment]
Hm, da kann ich mich nicht erinnern... Nimm's mal raus, wenn alles noch funktioniert wird's nicht gebraucht :slightly_smiling_face:
