### ISSUE TITLE
django-sendfile ggf. ersetzen

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#241]
django-sendfile [scheint ziemlich tot zu sein](https://github.com/johnsensible/django-sendfile): Letzte Änderung im Januar 2017, diverse pull-requests, maintainer scheint nicht erreichbar zu sein.

Mit #217 haben wir dann auch schon erste Workarounds im Code für fehlende django-sendfile-Funktionalität.

Ist wohl nur ne Frage der Zeit, bis da was kaputt geht (oder es ist schon was kaputt, und es war in den Tests bzw. der Development-Umgebung nicht sichtbar).

Alternativen die mir so einfallen:

- Selber schreiben (grad wenn wir eh wissen, welchen Webserver wir im Deployment haben)
- Redirect auf einen Pfad in `/static` oder so - ist aber die Frage, wie man das dann am besten mit Dokumenten macht, die ne Authentifizierung brauchen.
- [django-downloadview](https://github.com/benoitbryon/django-downloadview)

**Comment by The-Compiler** [comment]
Case in point: Nach dem Upgrade auf Python 3 sendet es: `Content-Disposition: attachment; filename="b'summary.txt'"; filename*=UTF-8''summary.txt` - für Browser die kein `filename*` können, würde das File also `b'summary.txt'` (inklusive `b'...'`) heissen.

Der Teil funktioniert aber ggf. zufällig nach #217 wieder.

**Comment by fabianhauser** [comment]
@The-Compiler wie sieht es zur Zeit mit `django-sendfile` aus? Müsste das immernoch ersetzt werden?

**Comment by The-Compiler** [comment]
Jap, daran hat sich nix geändert - das Projekt ist weiterhin tot, und funktioniert in unserem Fall nur noch zufällig. Wird also früher oder später wohl noch ganz kaputt gehen.
