### ISSUE TITLE
Request for testing: new.studentenportal.ch

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#247]
Es ist soweit: https://new.studentenportal.ch/ scheint zu funktionieren - mit neuem Django, neuem Python, neuem Server, neuem Deployment mit ganz viel Docker und so, und überhaupt alles einmal neu und abgestaubt.

Bevor ich mich an die Datenmigration mache (vermutlich erst Sonntag oder kommende Woche) würde ich gerne ein bisschen testen, ob alles so funktioniert, wie's soll. Auf den ersten Blick ist das der Fall - aber klickt doch bitte auch noch etwas rum und guckt, ob ihr was zum Explodieren kriegt.

Ihr müsst euch dazu neu registrieren, wie gewohnt mit der HSR-Adresse - der Account ist unabhängig vom bestehenden Studentenportal-Account und alle Daten auf new.studentenportal.ch werden in einigen Tagen wieder gelöscht.

**Comment by The-Compiler** [comment]
Es ist vollbracht: www.studentenportal.ch zeigt auf den neuen Server! Falls noch irgendwelche Fehler auftreten sollten wir zwar ne Mail bekommen - aber schadet vielleicht nicht, falls ihr trotzdem noch kurz in diesem Issue was erwähnt.

Ich mach das mal zu - scheint nämlich soweit alles zu funktionieren!

**Comment by dbrgn** [comment]
Whoa, danke vielmals, @The-Compiler!
