### ISSUE TITLE
Production Docker-Container läuft lokal nicht

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#248]
Wenn ich lokal `docker-compose -f docker-compose-production.yml up --build ` mache (momentan noch im `deployment` branch), kriege ich:

```
Recreating 5c754f8b0e26_web_studentenportal_1 ... error

ERROR: for 5c754f8b0e26_web_studentenportal_1  Cannot start service studentenportal: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./start.sh\": stat ./start.sh: no such file or directory": unknown

ERROR: for studentenportal  Cannot start service studentenportal: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./start.sh\": stat ./start.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

Keine Ahnung was das soll. Sollte meiner Meinung nach funktionieren, und auf dem Server tut's auch...

**Comment by The-Compiler** [comment]
Hrmpf, jetzt krieg ich das auch im master-Branch, und auch mit dem dev-Setup. Das war vor einigen Tagen definitiv noch nicht so. Aber auch ein Downgrade von docker und docker-compose haben nicht geholfen...

**Comment by The-Compiler** [comment]
Einmal alle Container/Images/Volumes weggehauen und ohne Änderungen neu gebaut, jetzt geht's. Hach, Docker...

**Comment by fabianhauser** [comment]
So viel zu reproducibility 🙈
