### ISSUE TITLE
Verschiedene Docker-Container-Namen für docker-compose(-production).yml

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#250]
Momentan resultieren beide YML-Files in Containern wie `web_{studentenportal,postgres}_1`. Da sollte z.B. beim dev-File noch ein `_dev` oder sowas mit rein, damit die ohne Probleme beide ausgeführt werden können.

**Comment by Murthy10** [comment]
@The-Compiler trifft folgender Commit deine Erwartungen? https://github.com/studentenportal/web/commit/a16b241b4842c2dfc10a66a37eef4094edda82a3

Oder vielleicht kannst du zu diesem Issue etwas mehr Inhalt bezüglich deiner Absicht hinzufügen.
z. B. braucht es Anpassungen im nginx config, damit dieser nicht alles auf studentenportal.ch weiterleitet?

**Comment by The-Compiler** [comment]
Uff, ist schon ne Weile her, weiss grad nicht mehr was hier der Hintergrund war :sweat_smile: 

Ich glaube, ich bin in Probleme reingelaufen, als ich dev/prod parallel auf demselben Rechner ausführen wollte - die Namen der Container sind dann gleich, aber die Container selbst ja unterschiedlich.

Auf den ersten Blick sollte dein Commit also das Problem beheben.

**Comment by Murthy10** [comment]
Okay, gut, dann lass ich das mal so und erstelle einen PR. Danke dir :+1:
