### ISSUE TITLE
VSHSR -> open\HSR auf der Webseite?

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#251]
Momentan steht noch "Willkommen beim VSHSR Studentenportal" - nachdem inzwischen ja primär der open\HSR das Studentenportal unterhält, würds vermutlich Sinn machen, es auch das "open\HSR Studentenportal" zu nennen?

**Comment by The-Compiler** [comment]
Ich war mal so frech und hab das nach dem :+1: von @dbrgn gemacht und deployed. :tada:

**Comment by fabianhauser** [comment]
Merci @The-Compiler ! 🕺
