### ISSUE TITLE
Sponsoring-Logos auf studentenportal.ch aufräumen

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/web#255]
- "Hosted by nine" kann weg, nachdem nine nun ein regulärer Sponsor ist (siehe auch https://github.com/studentenportal/project/issues/3#issuecomment-600676297)
- Soll/darf Bruhin Software auch mit Logo unter den Partnern mit rein, statt unter "Powered by"? Das war zwar nicht explizit so vereinbart für studentenportal.ch, aber dann wärs konsistent mit openhsr.ch.
- Soll der Open\HSR auch mit Logo unter "Partner" drauf, anstatt im Text unten? Dann würde der Text nur noch auf Software/Plattformen referenzieren (Python, Django, Github), aber streng genommen ist Open\HSR wohl nicht "nur" Partner
- Infomaniak ist auf openhsr.ch aber nicht studentenportal.ch - soll das auch noch mit drauf?

Siehe auch https://github.com/openhsr/www.openhsr.ch/issues/108

**Comment by Murthy10** [comment]
@fabianhauser please clarify the 3 last listed bullet points.

**Comment by fabianhauser** [comment]
> Soll/darf Bruhin Software auch mit Logo unter den Partnern mit rein, statt unter "Powered by"? Das war zwar nicht explizit so vereinbart für studentenportal.ch, aber dann wärs konsistent mit openhsr.ch.

So weit ich mich erinnere, hatten wir im open\HSR-Vorstand mal abgesprochen, dass das für den Moment okay ist.  

@The-Compiler : Bitte einen entsprechenden Pull-Request mit deinem Logo aufmachen.

> Infomaniak ist auf openhsr.ch aber nicht studentenportal.ch - soll das auch noch mit drauf?

Das ist erledigt.

> Soll der Open\HSR auch mit Logo unter "Partner" drauf, anstatt im Text unten? Dann würde der Text nur noch auf Software/Plattformen referenzieren (Python, Django, Github), aber streng genommen ist Open\HSR wohl nicht "nur" Partner

Ja, das wäre besser, bitte umsetzen @Murthy10 👍
