### ISSUE TITLE
Dozent M.A.

### ISSUE THREAD

**Issue by turbotimon** [studentenportal/web#257]
Kann man M.A. als Dozent hinzufügen?

**Angaben**: https://www.hsr.ch/de/suche/personen/suchergebnisse-personen/person/dr-mario-amrein-5022498/

**Bild**: https://pd.zhaw.ch/portraet/images/amrm.jpg

Danke
Timon

**Comment by dbrgn** [comment]
Der Dozenten-Import ist seit langem kaputt (#198), aber man kann die Dozenten über das Admin-Interface manuell adden.

Man braucht dafür die "HSR-ID", die scheint aber in der URL enthalten zu sein (5022498).

**Comment by dbrgn** [comment]
Habe das mal gemacht, allerdings ohne Bild (die sind nicht in der Datenbank sondern im Filesystem).

Nachhaltig wäre aber sowieso, den Scraper neu zu schreiben (#198) :)

**Comment by turbotimon** [comment]
Super, dank dir!
