### ISSUE TITLE
Allow ost.ch domain for registration

### ISSUE THREAD

**Issue by Darnor** [studentenportal/web#261]
New HSR - now OST - students will only be issued a ost.ch email address.

We should consider allowing both hsr.ch and ost.ch for new users.

Filter here: https://github.com/studentenportal/web/blob/master/apps/front/forms.py#L40

**Comment by The-Compiler** [comment]
I thought I had already done this, but apparently not! :see_no_evil: 

We currently enforce the short form of the name (i.e. no dots in the mail address, `mmuster@hsr.ch` and not `melanie.muster@hsr.ch`. I think those aliases don't exist anymore for OST addresses, so we'd likely have to adjust that as well. Correct?

**Comment by dbrgn** [comment]
> We currently enforce the short form of the name 

I think the reason that I added this constraint is that it avoids duplicate registrations using both variants. But I guess that's not too important.

**Comment by The-Compiler** [comment]
I'd like to keep that constraint for `@hsr.ch` for that exact reason (some people accidentally created duplicate accounts because of it, IIRC), but I'm wondering if the same constraint should be made for `@ost.ch` or not.

**Comment by Darnor** [comment]
If I'm not mistaken there are no short form ost.ch addresses, so we should only accept the long form. Also since the hsr.ch address will no longer work sometimes next year - February 2021 being my latest information - maybe we should think about forcing users to change to their ost.ch address. Or we move over to something like [SWITCHaai](https://www.switch.ch/aai/), not sure how doable that is though to be honest...

**Comment by dbrgn** [comment]
AAI would be great, see #116.

(Note: I finished my studies at HSR in 2014 and will not be working on this, as it's quite a lot of work and requires quite a lot of paperwork and communication with HSR/OST. If a current student wants to pick this up, go ahead!)

**Comment by The-Compiler** [comment]
PR to allow @ost.ch: #262
