### ISSUE TITLE
Update account e-mail to ost.ch

### ISSUE THREAD

**Issue by flObvious** [studentenportal/web#264]

**Comment by dbrgn** [comment]
Unterstützung für @ost.ch-Adressen wurde bereits in #261 implementiert.

**Comment by The-Compiler** [comment]
Eine Frage, die sich vielleicht noch stellt: Was machen wir mit bestehenden Accounts? Die @hsr.ch-Adressen sollen ja schon relativ bald (März 21 oder so?) nicht mehr weitergeleitet werden. Aber wir finden vermutlich nicht einfach so ein Mapping von HSR-Kurzname zur OST-Mail...

**Comment by dbrgn** [comment]
Einloggen kann man sich ja trotzdem noch damit... :slightly_smiling_face: Ev. könnte man auch ein "e-mail ändern"-Formular implementieren, damit jeder seine Mailadresse selber anpassen kann. Ist auch für Alumni interessant.

**Comment by fabianhauser** [comment]
Wir sind am schauen wegen eduid login, das würde die ganze Sache deutlich vereinfachen 🙂
