### ISSUE TITLE
Remove public visibility option for documents

### ISSUE THREAD

**Issue by FunkyFabe** [studentenportal/web#265]
Aus rechtlichen Gründen dürfen keine Dokument ohne Login herunterladen.

- [ ] Entferne Visibility Checkbox (siehe screenshot) im Frontend
- [ ] Default Visibility sollte im Backend auf die Option gesetzt werden, dass Login für Download benötigt wird.

![image](https://user-images.githubusercontent.com/20421488/93492721-67d21880-f90b-11ea-895e-e60024f55cf6.png)

**Comment by dbrgn** [comment]
> Aus rechtlichen Gründen dürfen keine Dokument ohne Login herunterladen.

Hmm, wenn ich ein Merkblatt zu einem Thema schreibe, wieso darf man das aus rechtlichen Gründen nicht ohne Login herunterladen dürfen?

**Comment by fabianhauser** [comment]
Mein Vorschlag wäre, dass wir einfach die default-option ändern auf non-public. Wenn wir auf die eduid umstellen, können sich dann auch alumni (oder, wenn wir wollen, auch nichtstudierende) einloggen, und es sollte trotzdem weniger email wegen copyright-verstössen geben.

**Comment by fabianhauser** [comment]
@Murthy10 bitte wie besprochen für den Moment mal die Standard-Option umstellen. Danke!

**Comment by The-Compiler** [comment]
Wir haben ja schon eine Validierung, dass Prüfungen nicht öffentlich sind:

https://github.com/studentenportal/web/blob/0378c19ebd3ee943d7a81249b67db6d0d12870a3/apps/documents/forms.py#L35-L38

Was war denn hier konkret das Problem?

**Comment by Murthy10** [comment]
Der Wunsch ist nun beim Dokumenten upload den Default auf non public zustellen.
PR dazu https://github.com/studentenportal/web/pull/269
(da ich noch nicht all zu vertraut mit dem Repo bin wäre ein review sicherlich angebracht)

**Comment by The-Compiler** [comment]
> Der Wunsch ist nun beim Dokumenten upload den Default auf non public zustellen.

Der Teil ist mir klar, aber die Hintergründe hinter diesem Issue (bzw die ursprüngliche Formulierung von @FunkyFabe) nicht wirklich - was ist denn passiert?

**Comment by Murthy10** [comment]
Nach meinem Verständnis (und falls falsch @fabianhauser bitte korrigiere mich) ist das Problem, dass es "immer wieder" Beschwerden von Seiter der HSR/Ost (bzw. Professoren) bezüglich Inhalten die veröffentlicht wurden gabe, für welche die Studenten keine Rechte hatten diese zu veröffentlichen. Und mit diesem Schritt will man dem etwas entgegenwirken.

**Comment by dbrgn** [comment]
Ich denke "non-public by default" ist dafür eine gute Lösung.

**Comment by fabianhauser** [comment]
Implementiert mit #269
