### ISSUE TITLE
Ansehen von hochgeladenem Dokument nicht möglich

### ISSUE THREAD

**Issue by Ce-eM** [studentenportal/web#267]
Beim Hochladen von zweien meiner Zusammenfassungen habe ich festgestellt, dass das anschauen über das Portal anschliessend nicht möglich ist. Ich dachte zuerst, dass dies einfach unmittelbar nach dem hochladen der fall sei, aber anscheinend bleibt der Fehler bestehend. Auch das setzen des hackens, dass die Zusammenfassungen ohne login angeschaut werden können, hat nichts geändert. Die Dateien sind relativ gross 8MB und 9.6MB, das Maximum ist aber nach meinem Wissen 20MB also sollte dies eigentlich trotzdem funktionieren.

![grafik](https://user-images.githubusercontent.com/57260134/94667795-8d99ed00-030f-11eb-9d53-f991743d117c.png)

**Comment by The-Compiler** [comment]
Siehe https://github.com/studentenportal/deploy2020/issues/24

**Comment by The-Compiler** [comment]
Funktioniert jetzt wieder - in https://github.com/studentenportal/deploy2020/issues/24#issuecomment-701288677 gibts eine Erklärung, warum das Problem nur bei grösseren Dateien aufgetreten ist.
