### ISSUE TITLE
studentenportal Down - Connection refused

### ISSUE THREAD

**Issue by pesc** [studentenportal/web#317]
```
curl -v https://studentenportal.ch/                                                                                                                                                      
*   Trying 5.148.180.58...
* TCP_NODELAY set
* Connection failed
* connect to 5.148.180.58 port 443 failed: Connection refused
* Failed to connect to studentenportal.ch port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to studentenportal.ch port 443: Connection refused
```

![Screenshot 2021-01-24 at 11 00 03](https://user-images.githubusercontent.com/2048399/105626884-522dac00-5e33-11eb-8fc1-b619f9e841f2.png)

**Comment by pesc** [comment]
@fabianhauser / @The-Compiler könnte jemand von euch das rasch anschauen? Danke

**Comment by fabianhauser** [comment]
Ich konnte den Fehler beheben.

@jossdev @pesc : Wir sind auf der Suche nach neuen Maintainern (Mehr infos unter https://github.com/studentenportal/project/issues/6). Sowohl @The-Compiler wie ich sind schon länger nicht mehr Studierende - wäre daher cool, wenn ihr als aktuelle Nutzniesser vom Studentenportal etwas zurückgeben könntet!
