### ISSUE TITLE
Modulkalender

### ISSUE THREAD

**Issue by Luegg** [studentenportal/web#47]
Pro Modul ein Kalender, wo Deadlines, Testattermine etc. eingetragen werden können. Natürlich dazu eine Möglichkeit, das ganze im iCal bereitzustellen, damit die Kalender in Google Calendar oder sonstwo eingefügt werden können.
Viele werden wahrscheinlich einzelne Termine eh schon irgendwo eintragen. Wieso also nicht gleich für alle verfügbar machen?

**Comment by saspeed** [comment]
Ich schliesse diesen Vorschlag. Begründung: Wir können keine Verantwortung dafür übernehmen, dass die auf dem Studentenportal eingetragegen Termine wirklich korrekt oder vollständig sind, da diese sehr modulspezifisch und in manchen Fällen sogar teilnehmerabhängig sind.
