### ISSUE TITLE
Studentenportal login

### ISSUE THREAD

**Issue by tstost** [studentenportal/web#537]
Guten Tag

Ich bin mir nicht sicher ob ich den Account nie aktiviert habe oder ob es andere Probleme gibt ich kann mich jedoch nicht in das Studentenportal einloggen noch ein neues passwort anfordern oder einen account auf meine tom.stromer@ost.ch mail regristrieren.

Freundliche Grüsse
Tom

**Comment by The-Compiler** [comment]
Sorry, dass das eine halbe Ewigkeit gedauert hat - das ging wohl in den GitHub-Notifications unter. Für solche Dinge ist eine Mail an team@studentenportal.ch am besten.

Die Aktivierung war effektiv das Problem. Ich habe dich jetzt manuell freigeschaltet!
