### ISSUE TITLE
Registrierung fehlgeschlagen, Profil existiert bereits

### ISSUE THREAD

**Issue by FabianSuter** [studentenportal/web#629]
Ich wollte mich auf dem Portal registrieren mit folgender Mail: fabian.suter@ost.ch
Dabei erscheint nur diese Meldung: "fabian.suter ist schon registriert"
Ich habe mich selbst aber noch nie registriert und auch noch keine Mail dafür erhalten.

Besten Dank für die Hilfe im Voraus

Gruäss Fabian

**Comment by The-Compiler** [comment]
Es gibt tatsächlich schon einen User `fabian.suter`, registriert im 2016. Ich vermute, das ist ein anderer Fabian Suter, der vor der Migration von `hsr.ch` zu `ost.ch` abgeschlossen hatte, und daher hast du `fabian.suter@ost.ch` zugewiesen gekriegt.

Da der alte Fabian Suter sein Profil nie aktiviert/genutzt hatte, habe ich den User gelöscht - sollte nun also funktionieren.
