### ISSUE TITLE
Feedback Studiengang

### ISSUE THREAD

**Issue by petermanser** [studentenportal/web#71]
Eine Moeglichkeit, fuer Studierende Feedback an den Studierendenvertreter/Fachschaft des Studiengangs zu geben.
Diese Feedback besteht aus:
- Titel
- Beschreibung
- Author (User)

Es gibt dann die Moeglichkeit, solche Feedbacks zu voten/liken/+1, d.h. ein Feedback trifft die Meinung vieler, wenn es oft gevoted wird. Dieses soll fuer alle Studiengaenge (separiert) verfuegbar sein.

**Comment by saspeed** [comment]
Eine solche Funktionalität wäre eine Art Tool für die Studiengangsvertreter, welche zu einem bestimmten Zeitpunkt im Semester eine Art Umfrage durchführen können. Für diesen Use Case gibt es schon wesentlich bessere Tools als wir es im Studentenportal einfach umsetzen könnten. Zudem ergibt sich für mich kein Wert in der längerfristigen Speicherung der Fragen und Antworten dieser Umfragen für andere Studenten. Von Datenschutz- und Subjektivitätsproblemen des jeweiligen Jahrgangs, einmal abgesehen. Ein mögliches Addin für die Startseite wären kurze Umfragen wie "Wo isst du lieber - Mensa oder Bistro?", "Rattenfest vs. Zürifest", was man beim update der Startseite zusammen mit #69 umsetzen könnte.
